global:
  dockerBase: "zerokai"

replicaCount: 1

image:
  repo: zk-observer
  tag: "latest"
  pullPolicy: Always

kubernetesClusterDomain: cluster.local

serviceConfigs:
  logs:
    color: true
    level: DEBUG

ports:
- port: 80
  protocol: TCP
  targetPort: 8147
  nodePort: 31602

type: NodePort
