kubernetesClusterDomain: cluster.local
zkOtlpReceiver:
  otlpConfigYaml: |-
    port: 8147
    setHttpEndPoint: true
    setSpanAttributes: true
    traces:
      syncDuration: 10000 #millis
      batchSize: 30
      ttl: 1800
    workloads:
      syncDuration: 10000 #millis
      batchSize: 30
      ttl: 1800
    redis:
     port: 6379
     dbs:
      filtered_traces: 1
      scenarios: 2
      traces: 3
      pod_details: 7
      error_details: 8
    logs:
      color: true
      level: DEBUG
    scenario:
      syncDuration: 30 #seconds
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8147
  replicas: 1
  type: ClusterIP
  zkOtlpReceiver:
    image:
      repository: us-west1-docker.pkg.dev/zerok-dev/stage/zk-otlp-receiver
      tag: dev
    imagePullPolicy: Always
