kubernetesClusterDomain: cluster.local
zkOtlpReceiver:
  otlpConfigYaml: |-
    port: 8147
    setHttpEndPoint: true
    setSpanAttributes: true
    traces:
      syncDuration: 10000 #millis
      timerDuration: 5000 #millis
      batchSize: 30
      ttl: 1800
    workloads:
      syncDuration: 10000 #millis
      timerDuration: 5000 #millis
      batchSize: 30
      ttl: 1800
    redis:
     port: 6379
     dbs:
      traces: 3
      exception: 8
      resource: 5
      scenario_db: 2
      workloads: 1
    logs:
      color: true
      level: DEBUG
    scenario:
      syncDuration: 30 #seconds
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8147
  replicas: 1
  type: ClusterIP
  zkOtlpReceiver:
    image:
      repository: us-west1-docker.pkg.dev/zerok-dev/stage/zk-otlp-receiver
      tag: dev
    imagePullPolicy: Always
