global:
  dockerBase: "us-west1-docker.pkg.dev/zerok-dev/stage/"

image:
  repo: zk-otlp-receiver
  tag: "latest"
  pullPolicy: Always

kubernetesClusterDomain: cluster.local

serviceConfigs:
  logs:
    color: true
    level: DEBUG

ports:
- port: 80
  protocol: TCP
  targetPort: 8147

type: ClusterIP
