apiVersion: v1
data:
  otlp-config.yaml: |+
    port: 8147
    setHttpEndPoint: true
    setSpanAttributes: true
    traces:
      syncDuration: 10000 #millis
      batchSize: 30
      ttl: 1800
    workloads:
      syncDuration: 10000 #millis
      batchSize: 30
      ttl: 1800
    resources:
      syncDuration: 10000 #millis
      batchSize: 30
    exceptions:
      syncDuration: 10000 #millis
      batchSize: 30
    redis:
     port: 6379
     dbs:
      filtered_traces: 1
      scenarios: 2
      traces: 3
      pod_details: 7
      error_details: 8
    logs:
      color: true
      level: DEBUG
    scenario:
      syncDuration: 30 #seconds
kind: ConfigMap
metadata:
  name: zk-otlp-receiver