apiVersion: v1
data:
  otlp-config.yaml: |+
    port: 8147
    redis:
     host: redis-master.zk-client.svc.cluster.local
     port: 6379
     ttl: 1800 #seconds
     batchSize: 30
     timerDuration: 5000 #millis
     syncDuration: 10000 #millis
     dbs:
      traces: 3
    logs:
      color: true
      level: DEBUG
kind: ConfigMap
metadata:
  name: zk-otlp-receiver