apiVersion: v1
data:
  otlp-config.yaml: |+
    port: 8147
    setHttpEndPoint: true
    setSpanAttributes: true
    traces:
      syncDuration: 10000 #millis
      timerDuration: 5000 #millis
      batchSize: 30
      ttl: 1800
    workloads:
      syncDuration: 10000 #millis
      timerDuration: 5000 #millis
      batchSize: 30
      ttl: 1800
    redis:
     port: 6379
     dbs:
      traces: 3
      exception: 8
      resource: 5
      scenario_db: 6
      workloads: 1
    logs:
      color: true
      level: DEBUG
    scenario:
      syncDuration: 30 #seconds
kind: ConfigMap
metadata:
  name: zk-otlp-receiver