port: 8147
redis:
  host: localhost
  port: 6379
  ttl: 1800 #seconds
  batchSize: 100
  timerDuration: 10000 #millis
  syncDuration: 20000 #millis
  dbs:
    traces: 3
logs:
  color: true
  level: DEBUG