apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: zk-otlp-receiver
  labels:
  {{- include "helm-charts.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app: zk-otlp-receiver
    {{- include "helm-charts.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: zk-otlp-receiver
      {{- include "helm-charts.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - env:
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ quote .Values.kubernetesClusterDomain }}
        - name: NODE_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: "ZK_REDIS_PASSWORD"
          value: eKbbxAn8qr
{{/*          valueFrom:*/}}
{{/*            secretKeyRef:*/}}
{{/*              name: "redis"*/}}
{{/*              key: "redis-password"*/}}
        - name: "ZK_REDIS_HOST" # Setting Redis password from Secret
          value: redis-master.zk-client.svc.cluster.local
{{/*          valueFrom:*/}}
{{/*            configMapKeyRef:*/}}
{{/*              name: "zk-redis-config"*/}}
{{/*              key: "redisHost"*/}}
        image: {{.Values.global.dockerBase}}/{{.Values.image.repo}}:{{.Values.image.tag}}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        name: zk-otlp-receiver
#        command: ["/bin/sh"]
#        args: ["-c", "dlv --listen=:2345 --headless=true --api-version=2 --accept-multiclient exec /zk/zk-otlp-receiver-arm64 -- -c /zk/config/config.yaml"]
        ports:
        - containerPort: 8147
        - containerPort: 8047
          hostPort: 31603
        resources: {}
        volumeMounts:
        - mountPath: /zk/config
          name: otlp-config
        - mountPath: /zk/badger-db
          name: badger-data
      volumes:
      - configMap:
          name: zk-otlp-receiver
        name: otlp-config
      - name: badger-data
        emptyDir: {}
{{/*        persistentVolumeClaim:*/}}
{{/*          claimName: zerok-badger-pvc*/}}
{{/*          readOnly: false*/}}