apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zerok-badger-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: zerok-badger-sc
  resources:
    requests:
      storage: 1Gi
