apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: opentelemetry
  namespace: opentelemetry-operator-system
spec:
  mode: daemonset
  hostNetwork: true
  config: |
    receivers:
      otlp:
        protocols:
          grpc:
          http:
      otlp/zerok:
         protocols:
          grpc:
            endpoint: 0.0.0.0:4319
          http:
            endpoint: 0.0.0.0:4320
    exporters:
      otlphttp/zerok:
        endpoint: http://0.0.0.0:31602
        compression: "none"
        tls:
          insecure: true
      otlp/jaeger:
        endpoint: http://jaeger.default.svc.cluster.local:4317
        tls:
          insecure: true
    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: []
          exporters: [otlphttp/zerok]
        traces/filtered:
          receivers: [otlp/zerok]
          processors: []
          exporters: [otlp/jaeger, otlphttp/zerok]