apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: zk-ebpf-node-view
  labels:
    app: zk-observer
    component: vizier
  {{- include "helm-charts.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - watch
  - list