apiVersion: v1
kind: Service
metadata:
  name: zk-ebpf-nats
  labels:
    app: zk-observer
    name: zk-ebpf-nats
  {{- include "helm-charts.labels" . | nindent 4 }}
spec:
  type: {{ .Values.plNats.type }}
  selector:
    app: zk-observer
    name: zk-ebpf-nats
  ports:
	{{- .Values.plNats.ports | toYaml | nindent 2 -}}