apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: zk-ebpf-metadata-role
  labels:
    app: zk-observer
    component: vizier
  {{- include "helm-charts.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - endpoints
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - create
- apiGroups:
  - coordination.k8s.io
  resourceNames:
  - metadata-election
  resources:
  - leases
  verbs:
  - get
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: zk-ebpf-metadata
  labels:
    app: zk-observer
    component: vizier
  {{- include "helm-charts.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - endpoints
  - namespaces
  verbs:
  - watch
  - get
  - list
- apiGroups:
  - apps
  resources:
  - replicasets
  - deployments
  verbs:
  - watch
  - get
  - list