apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: opentelemetry
spec:
  mode: daemonset
  hostNetwork: true
  config: |
    receivers:
      otlp:
        protocols:
          http:
      otlp/grpc:
        protocols:
          grpc:
    exporters:
      otlphttp: 
        endpoint: http://0.0.0.0:31600
        compression: "none"
      otlp:
        endpoint: http://0.0.0.0:31601
        compression: "none"
        tls:
          insecure: true
    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: []
          exporters: [otlphttp]
        traces/grpc:
          receivers: [otlp/grpc]
          processors: []
          exporters: [otlp]